### ISSUE TITLE
use components to build i, j, tbar

### ISSUE THREAD

**Issue by DunwichType** [aoifemooney/makingbiorhyme#12]
Glyphs such as  i, j, tbar should be built with components. This will make changes to the file easier to manage and reduce file sizes.

**Comment by aoifemooney** [comment]
Not sure what you mean here, James... I have not built any of the alphabetics using components barring the accented characters... What would I make these out of? The tbar is not made with components because the weight of the crossbar in the heaviest weights gets thinned to optically compensate for the density of the form with the extra bar, and this has to mirror the lightest weight for interpolation. For the i and j, these are using components in the accented versions, just not the base glyphs... Can you elaborate? =)

**Comment by aoifemooney** [comment]
Ah, was this related to the j sidebearing issue I wonder? Are you just suggesting I use a dot component for the i and j? @DunwichType

**Comment by davelab6** [comment]
Eg, make a dotlessi and dotlessj and unencoded tittle glyph, and compose
the i and j out of them

**Comment by davelab6** [comment]
(Since you need dotlessi and dotlessj anyway for Turkish etc)

**Comment by DunwichType** [comment]
> Ah, was this related to the j sidebearing issue I wonder? 

Yes. Of course the way auto-align keeps getting broken by Glyphs 2.3 does make me reconsider that stance ;)

> Are you just suggesting I use a dot component for the i and j?

Yes. Using components also keeps tittles and dot accents in sync. When I looked at BioRhyme the size and height of tittles and dot accents varied slightly. Conventional wisdom from the nations that use dot accents is that they should match tittles. Not adjusting them differently can seem awkward from the tradition of making everything balance optically, but it’s what the readers like.

**Comment by aoifemooney** [comment]
Ah, I get ya! So but in this case the 't' is ok though, right? given that I have had to make optical changes at different sizes? So I thought I had lined up the tittle/dot accent anchor so they were identical—oops! I will make these from components! Do you recommend using just the dot accent to build the i, or creating another component just to build these?

**Comment by davelab6** [comment]
If the dot accent is already identical to the tittles, then sure, why not
use it :)

For the t, since you can 'transform' components to a different W:H ratio
(and rotate and shear), and a rectangle transformed is not distorted, then
I expect you can still do the optical changes using a component..?

**Comment by aoifemooney** [comment]
Hi @davelab6! Ok, will do!

**Comment by aoifemooney** [comment]
I was worried the dot accent thing might confuse some text-setting systems, but you know my technological skillz, so I was probably unnecessarily worrying about that ;)

**Comment by davelab6** [comment]
I'm pretty sure it doesn't matter that a component parent is encoded :)

**Comment by aoifemooney** [comment]
Ok I updated these forms in the latest. I realized that actually the reason I wasn't using a component for the tbar was that not just the bar but also the crossbar of the t in the heavier weights was being adjusted, which meant I would have had to build the t as a base with a crossbar component. This seemed overly complicated, so I just changed the design to keep a heavy crossbar in the heavier weights. I was probably over-thinking it. Fixed in latest v1.5.

**Comment by DunwichType** [comment]
IIRC I listed tbar because the sidebearings were off. I should have
suggested just setting them to ==t in weights where tbar and t have the
same value.
On Apr 30, 2016 12:31 PM, "aoifemooney" notifications@github.com wrote:

Ok I updated these forms in the latest. I realized that actually the reason
I wasn't using a component for the tbar was that not just the bar but also
the crossbar of the t in the heavier weights was being adjusted, which
meant I would have had to build the t as a base with a crossbar component.
This seemed overly complicated, so I just changed the design to keep a
heavy crossbar in the heavier weights. I was probably over-thinking it.
Fixed in latest v1.5.
